apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  labels:
    app: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: devops-demo
        image: nandhuacr123.azurecr.io/devops-demo:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
spec:
  type: LoadBalancer
  selector:
    app: devops-demo
  ports:
  - port: 80
    targetPort: 3000
